blank_issues_enabled: false
contact_links:
  - name: Вопрос по использованию
    url: https://github.com/aliksandrkarankevich-sudo/cachyos-drive-card/discussions
    about: Вопросы, которые не являются ошибками или запросами функций
